/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLaboratorioRouteImport } from './routes/_app/laboratorio'
import { Route as AppGanhosRouteImport } from './routes/_app/ganhos'
import { Route as AppFluxoCaixaRouteImport } from './routes/_app/fluxo-caixa'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContasReceberRouteImport } from './routes/_app/contas-receber'
import { Route as AppContasRouteImport } from './routes/_app/contas'
import { Route as AppConsultorioRouteImport } from './routes/_app/consultorio'
import { Route as AppConsultasRouteImport } from './routes/_app/consultas'
import { Route as AppCadastrosRouteImport } from './routes/_app/cadastros'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLaboratorioRoute = AppLaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => AppRoute,
} as any)
const AppGanhosRoute = AppGanhosRouteImport.update({
  id: '/ganhos',
  path: '/ganhos',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoCaixaRoute = AppFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContasReceberRoute = AppContasReceberRouteImport.update({
  id: '/contas-receber',
  path: '/contas-receber',
  getParentRoute: () => AppRoute,
} as any)
const AppContasRoute = AppContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultorioRoute = AppConsultorioRouteImport.update({
  id: '/consultorio',
  path: '/consultorio',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultasRoute = AppConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosRoute = AppCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cadastros': typeof AppCadastrosRoute
  '/consultas': typeof AppConsultasRoute
  '/consultorio': typeof AppConsultorioRoute
  '/contas': typeof AppContasRoute
  '/contas-receber': typeof AppContasReceberRoute
  '/dashboard': typeof AppDashboardRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/ganhos': typeof AppGanhosRoute
  '/laboratorio': typeof AppLaboratorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cadastros': typeof AppCadastrosRoute
  '/consultas': typeof AppConsultasRoute
  '/consultorio': typeof AppConsultorioRoute
  '/contas': typeof AppContasRoute
  '/contas-receber': typeof AppContasReceberRoute
  '/dashboard': typeof AppDashboardRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/ganhos': typeof AppGanhosRoute
  '/laboratorio': typeof AppLaboratorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/cadastros': typeof AppCadastrosRoute
  '/_app/consultas': typeof AppConsultasRoute
  '/_app/consultorio': typeof AppConsultorioRoute
  '/_app/contas': typeof AppContasRoute
  '/_app/contas-receber': typeof AppContasReceberRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/_app/ganhos': typeof AppGanhosRoute
  '/_app/laboratorio': typeof AppLaboratorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cadastros'
    | '/consultas'
    | '/consultorio'
    | '/contas'
    | '/contas-receber'
    | '/dashboard'
    | '/fluxo-caixa'
    | '/ganhos'
    | '/laboratorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cadastros'
    | '/consultas'
    | '/consultorio'
    | '/contas'
    | '/contas-receber'
    | '/dashboard'
    | '/fluxo-caixa'
    | '/ganhos'
    | '/laboratorio'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/cadastros'
    | '/_app/consultas'
    | '/_app/consultorio'
    | '/_app/contas'
    | '/_app/contas-receber'
    | '/_app/dashboard'
    | '/_app/fluxo-caixa'
    | '/_app/ganhos'
    | '/_app/laboratorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/laboratorio': {
      id: '/_app/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof AppLaboratorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ganhos': {
      id: '/_app/ganhos'
      path: '/ganhos'
      fullPath: '/ganhos'
      preLoaderRoute: typeof AppGanhosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxo-caixa': {
      id: '/_app/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AppFluxoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas-receber': {
      id: '/_app/contas-receber'
      path: '/contas-receber'
      fullPath: '/contas-receber'
      preLoaderRoute: typeof AppContasReceberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas': {
      id: '/_app/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AppContasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultorio': {
      id: '/_app/consultorio'
      path: '/consultorio'
      fullPath: '/consultorio'
      preLoaderRoute: typeof AppConsultorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultas': {
      id: '/_app/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof AppConsultasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cadastros': {
      id: '/_app/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AppCadastrosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCadastrosRoute: typeof AppCadastrosRoute
  AppConsultasRoute: typeof AppConsultasRoute
  AppConsultorioRoute: typeof AppConsultorioRoute
  AppContasRoute: typeof AppContasRoute
  AppContasReceberRoute: typeof AppContasReceberRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFluxoCaixaRoute: typeof AppFluxoCaixaRoute
  AppGanhosRoute: typeof AppGanhosRoute
  AppLaboratorioRoute: typeof AppLaboratorioRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCadastrosRoute: AppCadastrosRoute,
  AppConsultasRoute: AppConsultasRoute,
  AppConsultorioRoute: AppConsultorioRoute,
  AppContasRoute: AppContasRoute,
  AppContasReceberRoute: AppContasReceberRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFluxoCaixaRoute: AppFluxoCaixaRoute,
  AppGanhosRoute: AppGanhosRoute,
  AppLaboratorioRoute: AppLaboratorioRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
