/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPacientesRouteImport } from './routes/_app/pacientes'
import { Route as AppLaboratorioRouteImport } from './routes/_app/laboratorio'
import { Route as AppGanhosRouteImport } from './routes/_app/ganhos'
import { Route as AppFollowupRouteImport } from './routes/_app/followup'
import { Route as AppFluxoCaixaRouteImport } from './routes/_app/fluxo-caixa'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContasReceberRouteImport } from './routes/_app/contas-receber'
import { Route as AppContasRouteImport } from './routes/_app/contas'
import { Route as AppConsultorioRouteImport } from './routes/_app/consultorio'
import { Route as AppConsultasRouteImport } from './routes/_app/consultas'
import { Route as AppCadastrosRouteImport } from './routes/_app/cadastros'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppLaboratorioRoute = AppLaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => AppRoute,
} as any)
const AppGanhosRoute = AppGanhosRouteImport.update({
  id: '/ganhos',
  path: '/ganhos',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowupRoute = AppFollowupRouteImport.update({
  id: '/followup',
  path: '/followup',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoCaixaRoute = AppFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContasReceberRoute = AppContasReceberRouteImport.update({
  id: '/contas-receber',
  path: '/contas-receber',
  getParentRoute: () => AppRoute,
} as any)
const AppContasRoute = AppContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultorioRoute = AppConsultorioRouteImport.update({
  id: '/consultorio',
  path: '/consultorio',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultasRoute = AppConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosRoute = AppCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cadastros': typeof AppCadastrosRoute
  '/consultas': typeof AppConsultasRoute
  '/consultorio': typeof AppConsultorioRoute
  '/contas': typeof AppContasRoute
  '/contas-receber': typeof AppContasReceberRoute
  '/dashboard': typeof AppDashboardRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/followup': typeof AppFollowupRoute
  '/ganhos': typeof AppGanhosRoute
  '/laboratorio': typeof AppLaboratorioRoute
  '/pacientes': typeof AppPacientesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cadastros': typeof AppCadastrosRoute
  '/consultas': typeof AppConsultasRoute
  '/consultorio': typeof AppConsultorioRoute
  '/contas': typeof AppContasRoute
  '/contas-receber': typeof AppContasReceberRoute
  '/dashboard': typeof AppDashboardRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/followup': typeof AppFollowupRoute
  '/ganhos': typeof AppGanhosRoute
  '/laboratorio': typeof AppLaboratorioRoute
  '/pacientes': typeof AppPacientesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/cadastros': typeof AppCadastrosRoute
  '/_app/consultas': typeof AppConsultasRoute
  '/_app/consultorio': typeof AppConsultorioRoute
  '/_app/contas': typeof AppContasRoute
  '/_app/contas-receber': typeof AppContasReceberRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/_app/followup': typeof AppFollowupRoute
  '/_app/ganhos': typeof AppGanhosRoute
  '/_app/laboratorio': typeof AppLaboratorioRoute
  '/_app/pacientes': typeof AppPacientesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cadastros'
    | '/consultas'
    | '/consultorio'
    | '/contas'
    | '/contas-receber'
    | '/dashboard'
    | '/fluxo-caixa'
    | '/followup'
    | '/ganhos'
    | '/laboratorio'
    | '/pacientes'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cadastros'
    | '/consultas'
    | '/consultorio'
    | '/contas'
    | '/contas-receber'
    | '/dashboard'
    | '/fluxo-caixa'
    | '/followup'
    | '/ganhos'
    | '/laboratorio'
    | '/pacientes'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/cadastros'
    | '/_app/consultas'
    | '/_app/consultorio'
    | '/_app/contas'
    | '/_app/contas-receber'
    | '/_app/dashboard'
    | '/_app/fluxo-caixa'
    | '/_app/followup'
    | '/_app/ganhos'
    | '/_app/laboratorio'
    | '/_app/pacientes'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laboratorio': {
      id: '/_app/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof AppLaboratorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ganhos': {
      id: '/_app/ganhos'
      path: '/ganhos'
      fullPath: '/ganhos'
      preLoaderRoute: typeof AppGanhosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/followup': {
      id: '/_app/followup'
      path: '/followup'
      fullPath: '/followup'
      preLoaderRoute: typeof AppFollowupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxo-caixa': {
      id: '/_app/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AppFluxoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas-receber': {
      id: '/_app/contas-receber'
      path: '/contas-receber'
      fullPath: '/contas-receber'
      preLoaderRoute: typeof AppContasReceberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas': {
      id: '/_app/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AppContasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultorio': {
      id: '/_app/consultorio'
      path: '/consultorio'
      fullPath: '/consultorio'
      preLoaderRoute: typeof AppConsultorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultas': {
      id: '/_app/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof AppConsultasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cadastros': {
      id: '/_app/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AppCadastrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCadastrosRoute: typeof AppCadastrosRoute
  AppConsultasRoute: typeof AppConsultasRoute
  AppConsultorioRoute: typeof AppConsultorioRoute
  AppContasRoute: typeof AppContasRoute
  AppContasReceberRoute: typeof AppContasReceberRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFluxoCaixaRoute: typeof AppFluxoCaixaRoute
  AppFollowupRoute: typeof AppFollowupRoute
  AppGanhosRoute: typeof AppGanhosRoute
  AppLaboratorioRoute: typeof AppLaboratorioRoute
  AppPacientesRoute: typeof AppPacientesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCadastrosRoute: AppCadastrosRoute,
  AppConsultasRoute: AppConsultasRoute,
  AppConsultorioRoute: AppConsultorioRoute,
  AppContasRoute: AppContasRoute,
  AppContasReceberRoute: AppContasReceberRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFluxoCaixaRoute: AppFluxoCaixaRoute,
  AppFollowupRoute: AppFollowupRoute,
  AppGanhosRoute: AppGanhosRoute,
  AppLaboratorioRoute: AppLaboratorioRoute,
  AppPacientesRoute: AppPacientesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
